tidy  code

diff --git a/deps/jansson/test/suites/invalid/run b/deps/jansson/test/suites/invalid/run
--- a/deps/jansson/test/suites/invalid/run
+++ b/deps/jansson/test/suites/invalid/run
@@ -13,18 +13,24 @@ do_run() {
     variant=$1
     s=".$1"
 
-    strip=""
+    strip=0
     if [ "$variant" = "strip" ]; then
         # This test should not be stripped
         [ -f $test_path/nostrip ] && return
-        strip="--strip"
+        strip=1
     fi
 
-    if ! $json_process $strip $test_path >$test_log/stdout$s 2>$test_log/stderr$s; then
-        echo $variant >$test_log/variant
+    STRIP=$strip $json_process --env \
+        <$test_path/input >$test_log/stdout$s 2>$test_log/stderr$s
+    valgrind_check $test_log/stderr$s || return 1
+
+    ref=error
+    [ -f $test_path/error$s ] && ref=error$s
+
+    if ! cmp -s $test_path/$ref $test_log/stderr$s; then
+        echo $variant > $test_log/variant
         return 1
     fi
-    valgrind_check $test_log/stderr$s || return 1
 }
 
 run_test() {
@@ -38,7 +44,14 @@ show_error() {
     s=".$variant"
 
     echo "VARIANT: $variant"
-    cat $test_log/stderr$s
+
+    echo "EXPECTED ERROR:"
+    ref=error
+    [ -f $test_path/error$s ] && ref=error$s
+    nl -bn $test_path/$ref
+
+    echo "ACTUAL ERROR:"
+    nl -bn $test_log/stderr$s
 }
 
 . $top_srcdir/test/scripts/run-tests.sh
